[build]
target = ".cargo/mips64vr-n64-elfeabi64.json"
rustc-wrapper = "./wrapper.sh"

[unstable]
build-std = ["core", "alloc"]

[target.'cfg(true)']
runner = ["nust64", "--libdragon", "release", "--elf"]
rustflags = ["-Cllvm-args=-mmax-float-constant-insns=3 -mfix4300 -falign-functions=32"]
